# .slather.yml

input_format: profdata
coverage_service: cobertura_xml
scheme: TopGames
workspace: TopGames.xcworkspace
xcodeproj: TopGames.xcodeproj
output_directory: coverage
ignore:
  - "ThirdParty/*"