# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    # Do something here before all lanes execution
    cocoapods
  end

  desc "Run all tests"
  lane :tests do
    scan
    swiftlint
    slather
  end

  after_all do |lane|
    # Do something here after all lanes execution
  end

  error do |lane, exception|
    # Do something here if get an error
  end
  
end
